# student.conf
# This file is used for TA grading purposes.
# Please fill out your personal information correctly.
# GITHUB_USERNAME must match the account you use to push to GitHub Classroom.

STUDENT_ID="b123456789"
STUDENT_NAME="Name"
GITHUB_USERNAME="id"
