# student.conf
# This file is used for TA grading purposes.
# Please fill out your personal information correctly.
# GITHUB_USERNAME must match the account you use to push to GitHub Classroom.

STUDENT_ID="R14946009"
STUDENT_NAME="R14946009"
GITHUB_USERNAME="R14946009"
